force-app/main/default/objects/DC_Action__mdt/DC_Action__mdt.object-meta.xml
<CustomObject>
    <label>DC_Action</label>
    <pluralLabel>DC_Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Action__mdt/fields/DC_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>DC_Wrapper__c</fullName>
    <label>DC_Wrapper</label>
    <referenceTo>DC_Wrapper__mdt</referenceTo>
    <relationshipLabel>DC_Actions</relationshipLabel>
    <relationshipName>DC_Actions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DC_Action__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Row</fullName>
                <default>true</default>
                <label>Row</label>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/DC_Field__mdt.object-meta.xml
<CustomObject>
    <label>DC_Field</label>
    <pluralLabel>DC_Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Field__mdt/fields/DC_Section__c.field-meta.xml
<CustomField>
    <fullName>DC_Section__c</fullName>
    <label>DC_Section</label>
    <referenceTo>DC_Section__mdt</referenceTo>
    <relationshipLabel>DC_Fields</relationshipLabel>
    <relationshipName>DC_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Is_Hidden_When_Empty__c.field-meta.xml
<CustomField>
    <fullName>Is_Hidden_When_Empty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hidden When Empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SF</fullName>
                <default>true</default>
                <label>SF</label>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/toLabel__c.field-meta.xml
<CustomField>
    <fullName>toLabel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>toLabel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>action-icon</fullName>
                <default>true</default>
                <label>action-icon</label>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>link-to-object</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>text-icon</fullName>
            </value>
            <value>
                <fullName>text-tooltip</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Wrapper__c</fullName>
    <label>Wrapper</label>
    <referenceTo>DC_Wrapper__mdt</referenceTo>
    <relationshipName>dc_fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DC_Section__mdt/DC_Section__mdt.object-meta.xml
<CustomObject>
    <label>DC_Section</label>
    <pluralLabel>DC_Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Section__mdt/fields/Default_Open__c.field-meta.xml
<CustomField>
    <fullName>Default_Open__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Default Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/DC_Wrapper__mdt.object-meta.xml
<CustomObject>
    <label>DC_Wrapper</label>
    <pluralLabel>DC_Wrappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Card_Header_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Header_Style__c</fullName>
    <label>Card Header Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Page Header</fullName>
                <default>true</default>
                <label>Page Header</label>
            </value>
            <value>
                <fullName>Einstein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Data_Path__c.field-meta.xml
<CustomField>
    <fullName>Data_Path__c</fullName>
    <label>Data Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <label>Display Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compact Layout</fullName>
                <default>true</default>
                <label>Compact Layout</label>
            </value>
            <value>
                <fullName>Detail Page</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Hide_Card_Header__c.field-meta.xml
<CustomField>
    <fullName>Hide_Card_Header__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check when you want to remove card header</description>
    <label>Hide Card Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Illustration__c.field-meta.xml
<CustomField>
    <fullName>Illustration__c</fullName>
    <label>Illustration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Desert</fullName>
                <default>true</default>
                <label>Desert</label>
            </value>
            <value>
                <fullName>NoAssistant</fullName>
                <label>No Assistant</label>
            </value>
            <value>
                <fullName>NoEvents</fullName>
                <label>No Events</label>
            </value>
            <value>
                <fullName>NoTasks</fullName>
                <label>No Tasks</label>
            </value>
            <value>
                <fullName>OpenRoad</fullName>
                <label>Open Road</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Illustration_Size__c.field-meta.xml
<CustomField>
    <fullName>Illustration_Size__c</fullName>
    <label>Illustration Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>small</fullName>
            </value>
            <value>
                <fullName>large</fullName>
                <default>true</default>
                <label>large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Is_Nested_Card__c.field-meta.xml
<CustomField>
    <fullName>Is_Nested_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <description>click when your component inside another card and you want to show borders</description>
    <label>Is Nested Card</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Max_Row_Selection__c.field-meta.xml
<CustomField>
    <fullName>Max_Row_Selection__c</fullName>
    <inlineHelpText>The value should be a positive integer
Checkboxes are used for selection by default,
and radio buttons are used when maxRowSelection is 1
If zero or negetive is selected the row selection is hidden</inlineHelpText>
    <label>Max Row Selection</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/No_Data_Message__c.field-meta.xml
<CustomField>
    <fullName>No_Data_Message__c</fullName>
    <label>No Data Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <label>Service Endpoint</label>
    <referenceTo>Service_Endpoint__mdt</referenceTo>
    <relationshipName>dc_wrappers</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Show_Row_Number__c.field-meta.xml
<CustomField>
    <fullName>Show_Row_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Row Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Endpoint__mdt/Service_Endpoint__mdt.object-meta.xml
<CustomObject>
    <label>Service Endpoint</label>
    <pluralLabel>Service Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Endpoint__mdt/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <inlineHelpText>the url for the service (method) that comes after the domain,
example : /customer/add
start with &quot;/&quot;</inlineHelpText>
    <label>Service Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomComponent.cls
public with sharing class CustomComponent {

    @AuraEnabled(cacheable=true)
    public static WrapperInfo wireGetWrapperModel(String developerName) {
        DC_Wrapper__mdt wrapper = CustomComponent.getWrapperModel(developerName);
        return fillWrapperInfo(wrapper);
    }

    @AuraEnabled(cacheable=false)
    public static Object getClassResult(String apexClass, String recordId, String serviceEndpoint, Map<String,Object> calloutParams) {

        DCService service = (DCService) Type.forName(apexClass).newInstance();
        Map<String, Object> result = service.retrieve(recordId, serviceEndpoint, calloutParams);

        if (result != null && !result.IsEmpty()) {
            return result;
        }

        return null;
    }

    public static DC_Wrapper__mdt getWrapperModel(String developerName) {

        List<DC_Wrapper__mdt> wrappers = [
            SELECT Id, Label, Icon__c, Display_Type__c, Apex_Class__c,
            Is_Nested_Card__c, Hide_Card_Header__c, Card_Header_Style__c,
            Illustration__c, Illustration_Size__c, No_Data_Message__c, 
            Max_Row_Selection__c, Show_Row_Number__c,
            Service_Endpoint__r.DeveloperName, Data_Path__c,
            (SELECT Id, Label, Source__c, Order__c, Field_API_Name__c,Type__c,
            Is_Hidden_When_Empty__c, toLabel__c,
            DC_Section__c, DC_Section__r.DeveloperName, DC_Section__r.Label, 
            DC_Section__r.Order__c, DC_Section__r.Default_Open__c
            FROM dc_fields__r WHERE Active__c = true ORDER BY Order__c),
            (SELECT Id, Label, DeveloperName, Type__c, Flow_Name__c, Order__c 
            FROM DC_Actions__r WHERE Active__c = true ORDER BY Order__c)
        FROM  DC_Wrapper__mdt
        WHERE DeveloperName =: developerName LIMIT 1];

        if(!wrappers.isEmpty()){
            return wrappers[0];
        }
        
        return null;
    }

    public static WrapperInfo fillWrapperInfo(DC_Wrapper__mdt wrapper) {

        WrapperInfo wrapperInfo = null;

        if(wrapper != null){
            wrapperInfo = new WrapperInfo();
            wrapperInfo.title = wrapper.Label;
            wrapperInfo.icon = wrapper.Icon__c;
            wrapperInfo.type = wrapper.Display_Type__c;
            wrapperInfo.serviceEndpoint = wrapper.Service_Endpoint__r.DeveloperName;
            wrapperInfo.dataPath = wrapper.Data_Path__c;
            wrapperInfo.maxRowSelection = wrapper.Max_Row_Selection__c;
            wrapperInfo.showRowNumber = wrapper.Show_Row_Number__c;
            wrapperInfo.apexClass = wrapper.Apex_Class__c;
            wrapperInfo.isNestedCard = wrapper.Is_Nested_Card__c;
            wrapperInfo.hideHeader = wrapper.Hide_Card_Header__c;
            wrapperInfo.headerStyle = wrapper.Card_Header_Style__c;
            wrapperInfo.illustration = wrapper.Illustration__c;
            wrapperInfo.illustrationSize = wrapper.Illustration_Size__c;
            wrapperInfo.noDataMessage = wrapper.No_Data_Message__c;

            wrapperInfo.columns = getColumns(wrapper.Display_Type__c, wrapper.dc_fields__r);
            wrapperInfo.actions = getActions(wrapper.DC_Actions__r);
        }

        return wrapperInfo;
    }

    public static List<FieldInfo> getColumns(String wrapperType, List<DC_Field__mdt> fieldList) {
        List<FieldInfo> fieldInfoResult = new List<FieldInfo>();
        for (DC_Field__mdt oneField : fieldList) {

            String fieldType = oneField.Type__c;
            String formatter = '';

            if(wrapperType != 'Table' && (fieldType == 'currency' || fieldType == 'percent')){
                    formatter = fieldType;
                    fieldType = 'number';
            }

            FieldInfo fieldInfo = new fieldInfo(
                oneField.Field_API_Name__c, 
                oneField.Label,
                fieldType, 
                formatter,
                oneField.Source__c, 
                oneField.Is_Hidden_When_Empty__c);

            if(String.isNotBlank(oneField.DC_Section__c)){
                fieldInfo.section = new SectionInfo(
                    oneField.DC_Section__r.DeveloperName,
                    oneField.DC_Section__r.Label,
                    oneField.DC_Section__r.Order__c,
                    oneField.DC_Section__r.Default_Open__c                   
                );
            }

            fieldInfoResult.add(fieldInfo);
        }

        return fieldInfoResult;
    }

    public static List<ActionInfo> getActions(List<DC_Action__mdt> actionList){
        List<ActionInfo> actions = new List<ActionInfo>();
        for(DC_Action__mdt action : actionList){
            actions.add(new ActionInfo(
                action.Label,
                action.DeveloperName,
                action.Flow_Name__c,
                action.Type__c,
                action.Order__c 
            ));
        }
        return actions;
    }

    public class WrapperInfo {

        @AuraEnabled
        public String title {get;set;}

        @AuraEnabled
        public String icon {get;set;}

        @AuraEnabled
        public String type {get;set;}

        @AuraEnabled
        public String serviceEndpoint {get;set;}
        
        @AuraEnabled
        public String dataPath {get;set;}

        @AuraEnabled
        public Decimal maxRowSelection {get;set;}

        @AuraEnabled
        public Boolean showRowNumber {get;set;}

        @AuraEnabled
        public String apexClass {get;set;}

        @AuraEnabled
        public List<FieldInfo> columns {get;set;}

        @AuraEnabled
        public Boolean isNestedCard {get;set;}

        @AuraEnabled
        public Boolean hideHeader {get;set;}

        @AuraEnabled
        public String headerStyle {get;set;}

        @AuraEnabled
        public String illustration {get;set;}

        @AuraEnabled
        public String illustrationSize {get;set;}

        @AuraEnabled
        public String noDataMessage {get;set;}

        @AuraEnabled
        public List<ActionInfo> actions {get;set;}
    }

    public class SectionInfo {
        @AuraEnabled
        public String id {get;set;}  

        @AuraEnabled
        public String title {get;set;}  

        @AuraEnabled
        public Decimal order {get;set;}  

        @AuraEnabled
        public Boolean isDefaultOpen {get;set;} 

        public SectionInfo(){

        }

        public SectionInfo(String id, String title, Decimal Order, Boolean isDefaultOpen){
            this.id = id;
            this.title = title;
            this.order = order;
            this.isDefaultOpen = isDefaultOpen;
        }
    }

    public class FieldInfo {
        @AuraEnabled
        public String fieldName {get;set;}

        @AuraEnabled
        public String label {get;set;} 
        
        @AuraEnabled
        public String type {get;set;} 

        @AuraEnabled
        public String formatter {get;set;} 

        @AuraEnabled
        public String source {get;set;} 

        @AuraEnabled
        public Boolean isHiddenWhenEmpty {get;set;} 

        @AuraEnabled
        public SectionInfo section {get;set;} 

        public FieldInfo(){

        }

        public FieldInfo(String fieldName, String label, String type,String formatter, String source, Boolean isHiddenWhenEmpty){
            this.fieldName = fieldName;
            this.label = label;
            this.type = type;
            this.formatter = formatter;
            this.source = source;
            this.isHiddenWhenEmpty = isHiddenWhenEmpty;
        }
    }

    public class ActionInfo {
        @AuraEnabled
        public String label {get;set;}

        @AuraEnabled
        public String name {get;set;}

        @AuraEnabled
        public String flowName {get;set;}

        @AuraEnabled
        public String type {get;set;}

        @AuraEnabled
        public Decimal order {get;set;}

        public ActionInfo(){

        }

        public ActionInfo(String label, String name, String flowName, String type, Decimal order){
            this.label = label;
            this.name = name;
            this.flowName = flowName;
            this.type = type;
            this.order = order;
        }
    }
}