force-app/main/default/objects/DC_Field__mdt/DC_Field__mdt.object-meta.xml
<CustomObject>
    <label>DC_Field</label>
    <pluralLabel>DC_Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Field__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SF</fullName>
                <default>true</default>
                <label>SF</label>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>action-icon</fullName>
                <default>true</default>
                <label>action-icon</label>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>link-to-object</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>text-icon</fullName>
            </value>
            <value>
                <fullName>text-tooltip</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Field__mdt/fields/Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Wrapper__c</fullName>
    <label>Wrapper</label>
    <referenceTo>DC_Wrapper__mdt</referenceTo>
    <relationshipName>dc_fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/DC_Wrapper__mdt.object-meta.xml
<CustomObject>
    <label>DC_Wrapper</label>
    <pluralLabel>DC_Wrappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Card_Header_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Header_Style__c</fullName>
    <label>Card Header Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Page Header</fullName>
                <default>true</default>
                <label>Page Header</label>
            </value>
            <value>
                <fullName>Einstein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <label>Display Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compact Layout</fullName>
                <default>true</default>
                <label>Compact Layout</label>
            </value>
            <value>
                <fullName>Detail Page</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Illustration__c.field-meta.xml
<CustomField>
    <fullName>Illustration__c</fullName>
    <label>Illustration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Desert</fullName>
                <default>true</default>
                <label>Desert</label>
            </value>
            <value>
                <fullName>NoAssistant</fullName>
                <label>No Assistant</label>
            </value>
            <value>
                <fullName>NoEvents</fullName>
                <label>No Events</label>
            </value>
            <value>
                <fullName>NoTasks</fullName>
                <label>No Tasks</label>
            </value>
            <value>
                <fullName>OpenRoad</fullName>
                <label>Open Road</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Illustration_Size__c.field-meta.xml
<CustomField>
    <fullName>Illustration_Size__c</fullName>
    <label>Illustration Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>small</fullName>
            </value>
            <value>
                <fullName>large</fullName>
                <default>true</default>
                <label>large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Max_Row_Selection__c.field-meta.xml
<CustomField>
    <fullName>Max_Row_Selection__c</fullName>
    <inlineHelpText>The value should be a positive integer
Checkboxes are used for selection by default,
and radio buttons are used when maxRowSelection is 1
If zero or negetive is selected the row selection is hidden</inlineHelpText>
    <label>Max Row Selection</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/No_Data_Message__c.field-meta.xml
<CustomField>
    <fullName>No_Data_Message__c</fullName>
    <label>No Data Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Wrapper__mdt/fields/Show_Row_Number__c.field-meta.xml
<CustomField>
    <fullName>Show_Row_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Row Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomComponentTest.cls
@IsTest
private class CustomComponentTest {

    private static final String WRAPPER_NAME = 'Products_Table';

    static void generateDataModel(){
        
        DC_Wrapper__mdt wrapper = new DC_Wrapper__mdt(

            Label = 'מוצרים', 
            DeveloperName = WRAPPER_NAME,
            Icon__c = 'standard:account', 
            Display_Type__c = 'Table', 
            Card_Header_Style__c = 'Page Header',
            Illustration__c = 'No Events', 
            Illustration_Size__c = 'large', 
            No_Data_Message__c = '', 
            Max_Row_Selection__c = 10, 
            Show_Row_Number__c = true
        );

        // insert wrapper;

        DC_Field__mdt field1 = new DC_Field__mdt(
            Label = 'שם פרטי',
            DeveloperName = 'First_Name',
            Field_API_Name__c = 'firstName',
            Wrapper__c = wrapper.Id,
            Type__c = 'Text',
            Source__c = 'Service',
            Order__c = 1
        );
        
        DC_Field__mdt field2 = new DC_Field__mdt(
            Label = 'שם משפחה',
            DeveloperName = 'Last_Name',
            Field_API_Name__c = 'lastName',
            Wrapper__c = wrapper.Id,
            Type__c = 'Text',
            Source__c = 'Service',
            Order__c = 1
        );

        List<DC_Field__mdt> fields = new List<DC_Field__mdt>{ field1, field2 };

        // insert fields;
    } 
    
    @IsTest
    private static void generateDynamicComponent (){
        Test.startTest();
        CustomComponent.wireGetWrapperModel(WRAPPER_NAME);
        Test.stopTest();
    }
}